apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: systemd-analyse-exporter
spec:
  template:
    metadata:
      name: systemd-analyse-exporter
      labels:
        app: systemd-analyse-exporter
    spec:
      hostNetwork: true
      containers:
      - name: systemd-analyse-exporter
        image: quay.io/mad01/systemd-analyse-exporter:87365e4f599e24fc0614acfeaecdd2830a505a56
        imagePullPolicy: IfNotPresent
        ports:
          - name: http-metrics
            containerPort: 9011
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/run/dbus
          name: dbus
      volumes:
      - hostPath:
          path: /var/run/dbus
        name: dbus
